# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='unprayed_count',
            field=models.IntegerField(default=0),
        ),
    ]
