# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0004_auto_20151208_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='prayer_file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
