# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0005_prayer_prayer_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayer',
            name='prayer_file',
        ),
        migrations.AddField(
            model_name='prayer',
            name='email_subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
