# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0007_prayer_response_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='response_text',
            field=models.TextField(blank=True, default=b"We understand that spiritual growth is a journey, and there can be some obstacles along the way. But you don't have to face them alone.  \n\nThe goTandem team would be honored to pray for you. We also love to hear how God is working in your life. We encourage you to share your stories as well so we can celebrate with you.\n\nShare your prayer request or story with us simply by replying to this email.\n\nThanks for being a part of the goTandem community!\n", null=True),
        ),
    ]
