# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0011_auto_20160112_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='prayed_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='response_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='response_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
