# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0012_auto_20160114_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='response_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
