# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0014_auto_20160115_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
