# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0015_prayer_received_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'date uploaded')),
                ('file_name', models.CharField(max_length=100)),
            ],
        ),
    ]
